# gamma 1MeV 
/gun/particle ion
#/gun/particle geantino
/gun/ion 11 22
/gun/energy 0.0 MeV
/gun/position 0 0 0 mm

# change detector parameter
/PP1/det/setMaterial Scintillator
#/PP1/det/setThickness 0.15 mm
#/PP1/det/setSize   1. cm

# tracking verbose
/tracking/verbose 1

## coloring by Particle ID
/vis/modeling/trajectories/create/drawByParticleID Color
/vis/modeling/trajectories/Color/set e+ blue
/vis/modeling/trajectories/Color/set e- red
/vis/modeling/trajectories/Color/set gamma green
#/vis/modeling/trajectories/Color/set nu_e yellow
#/vis/modeling/trajectories/Color/default/setDrawStepPts true
/vis/modeling/trajectories/Color/default/setStepPtsSize 5
#/vis/modeling/trajectories/Color/default/setDrawAuxPts true
/vis/modeling/trajectories/Color/default/setAuxPtsSize 5
/control/alias interval 0,01
/control/alias halfInterval 0,005
#/vis/modeling/trajectories/Color/default/setTimeSliceInterval {interval} ns
/vis/modeling/trajectories/list

#Remove nu
/vis/filtering/trajectories/create/particleFilter ColorFilter
/vis/filtering/trajectories/ColorFilter/add nu_e
/vis/filtering/trajectories/ColorFilter/add gamma
/vis/filtering/trajectories/ColorFilter/invert true

# start event
# 10 M events
#/run/beamOn 10000000
/gun/particle geantino
/gun/energy 1 MeV
/gun/direction 1 0 0
/run/beamOn 10
